# Generated by Django 6.0.1 on 2026-03-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("group", models.CharField(max_length=50)),
                ("direction", models.CharField(max_length=100)),
                (
                    "year_of_study",
                    models.IntegerField(
                        choices=[
                            (1, "1-kurs"),
                            (2, "2-kurs"),
                            (3, "3-kurs"),
                            (4, "4-kurs"),
                            (5, "5-kurs"),
                        ]
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("parent_name", models.CharField(blank=True, max_length=200)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
