# Generated by Django 6.0.1 on 2026-03-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=20, unique=True)),
                ("specialization", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=100)),
                ("experience_years", models.IntegerField(default=0)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("department", models.CharField(max_length=100)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_full_time", models.BooleanField(default=True)),
                ("office_room", models.CharField(blank=True, max_length=20)),
                ("working_hours", models.IntegerField(default=40)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
